FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block xtrabackup_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel', 'ubuntu', 'debian'] %}
    {% set xtrabackup_packages = ['percona-xtrabackup'] %}
{% endif %}

{{ macros.install_packages(xtrabackup_packages | customizable("packages")) }}

{% block xtrabackup_footer %}{% endblock %}

{% block footer %}{% endblock %}

VOLUME /backup

COPY backup.sh /usr/local/bin/kolla_backup_mariadb.sh

CMD chmod 755 /usr/local/bin/kolla_backup_mariadb.sh && \
    /usr/local/bin/kolla_backup_mariadb.sh
